# Dependencies
markdown:         kramdown
highlighter:      rouge

gems: [jekyll-paginate]
gems: [jekyll-gist]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            НУГ
tagline:          'Дифференциальные уравнения и численные методы'
description:      'Сайт посвящен деятельности научно-учебной группы. Работа проведена в ходе исследования (16-05-0069)'
url:              http://hsemmsg.github.io/
baseurl:          http://hsemmsg.github.io/

author:
  name:           'Mark Otto'
  url:            http://hsemmsg.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hsemmsg/hsemmsg.github.io
