# Dependencies
markdown:         kramdown
highlighter:      rouge

gems: [jekyll-paginate]
gems: [jekyll-gist]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'НУГ'
tagline:          'Дифференциальные уравнения и численные методы'
description:      'НУГ "Дифференциальные уравнения и численные методы"'
url:              http://hsemmsg.github.io/
baseurl:          http://hsemmsg.github.io/

author:
  name:           'НУГ Дифференциальные уравнения и численные методы'
  url:            http://hsemmsg.github.io

paginate:         5

# Custom vars
version:          2.1.21

github:
  repo:           https://github.com/hsemmsg/hsemmsg.github.io
